# site settings
title: MyTravelCare
subtitle: by Evocare Srl
email: info@evocare.tech
# description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
description: Ogni anno viaggiano milioni e milioni di persone.<br/><br/>E la loro Salute?<br/><br/>In viaggio anche un piccolo problema può diventare fastidioso, la maggior parte di noi spera solo che vada tutto bene.<br/><br/>Noi abbiamo una soluzione migliore.<br/><br/>MyTravelCare ti permette di avere la tua Salute ovunque, a portata di mano, tradotta nella lingua che desideri.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Think3
street_address: 1234 Somewhere Road
city: Milano 
state: MI
zip_code: 20123
country: Italy
phone: (+39) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
